
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;
import tabel_pengiriman.CargoEntity;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI
 */
public class Cargo extends javax.swing.JFrame {
    private Statment St;
    private Connection Con;
    private Resultset Rs;
    private final String sql="";
    private DefaultTableModel DefaultTableModel;
    /**
     * Creates new form Cargo
     */
    public Cargo() {
        initComponents();
        KoneksiDatabase();
    }
    
    private void KoneksiDatabase(){
        try {
            //Menentukan Driver Database
            Class.forName("com.mysql.jdbc.Driver");
            // untuk mengkoneksikan DB ke driver 
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cargo", "root", "");
            // pesan koneksi berhasil
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            // pesan Koneksi gagal
            System.out.println("Koneksi Gagal"+ e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JComboBox<>();
        Bulan = new javax.swing.JComboBox<>();
        TFNama = new javax.swing.JTextField();
        TFAlamat = new javax.swing.JTextField();
        TFResi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EditJB = new javax.swing.JButton();
        DelJB = new javax.swing.JButton();
        SimpanJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Pengiriman Barang");

        jLabel2.setText("Nama Penerima");

        jLabel3.setText("Alamat Penerima");

        jLabel4.setText("Nomor Resi");

        jLabel5.setText("Tanggal Pengiriman");

        jLabel6.setText("Bulan Pengiriman");

        Tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari 2024", "Februari 2024", "Maret 2024", "April 2024", "Mei 2024", "Juni 2024", "Juli 2024", "Agustus 2024", "September 2024", "Oktober 2024", "November 2024", "Desember 2024", "" }));

        TFNama.setToolTipText("");
        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        EditJB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EditJB.setText("Edit");
        EditJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditJBActionPerformed(evt);
            }
        });

        DelJB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DelJB.setText("Delete");
        DelJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelJBActionPerformed(evt);
            }
        });

        SimpanJB.setText("Simpan");
        SimpanJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(SimpanJB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFNama, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFResi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tanggal, javax.swing.GroupLayout.Alignment.TRAILING, 0, 148, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(EditJB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(DelJB)
                                        .addGap(101, 101, 101))
                                    .addComponent(Bulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFResi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addComponent(SimpanJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditJB)
                    .addComponent(DelJB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void EditJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditJBActionPerformed
    String nama = TFNama.getText();
    String alamat = TFAlamat.getText();
    String resi = TFResi.getText();
    String tanggal = Tanggal.getSelectedItem().toString();
    String bulan = Bulan.getSelectedItem().toString();
    int id = Integer.parseInt(TFId.getText());

    Session session = HibernateUtil.getSessionFactory().openSession();
    Transaction tx = session.beginTransaction();

    try {
        CargoEntity cargo = (CargoEntity) session.get(CargoEntity.class, id);
        if (cargo != null) {
            cargo.setNama(nama);
            cargo.setAlamat(alamat);
            cargo.setResi(resi);
            cargo.setTanggal(tanggal);
            cargo.setBulan(bulan);

            session.update(cargo); // Update data
            tx.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        }
    } catch (HeadlessException e) {
        tx.rollback();
        JOptionPane.showMessageDialog(this, "Gagal mengupdate data: " + e.getMessage());
    } finally {
        session.close();
    }
  
    }//GEN-LAST:event_EditJBActionPerformed

    private void DelJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelJBActionPerformed
     int id = Integer.parseInt(TFId.getText());
     
    Session session = HibernateUtil.getSessionFactory().openSession();
    Transaction tx = session.beginTransaction();

    try {
        Object cargo = session.get(CargoEntity.class, id);
        if (cargo != null) {
            session.delete(cargo); // Hapus data
            tx.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        }
    } catch (HeadlessException e) {
        tx.rollback();
        JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    } finally {
        session.close();
        }


    }//GEN-LAST:event_DelJBActionPerformed

    private void SimpanJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanJBActionPerformed
    String nama = TFNama.getText();
    String alamat = TFAlamat.getText();
    String resi = TFResi.getText();
    String tanggal = Tanggal.getSelectedItem().toString();
    String bulan = Bulan.getSelectedItem().toString();

    if (!nama.isEmpty() && !alamat.isEmpty() && !resi.isEmpty()) {
         JOptionPane.showMessageDialog(null, "Semua kolom harus diisi!");
    } else {
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        JTable jTable1;
        jTable1 = new JTable(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Kolom 1", "Kolom 2", "Kolom 3", "Kolom 4",  "Kolom 5"}
        ));
        Object nama1 = TFNama.getText();
        Object alamat2 = TFAlamat.getText();
        Object resi3 = TFResi.getText();
        Object tanggal4 = Integer.parseInt(Tanggal.getSelectedItem().toString());
        Object bulan5;
        bulan5 = Integer.parseInt(Bulan.getSelectedItem().toString());
            if (nama1 == null || nama1.toString().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
        return;
        }
        // Hibernate Session
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.getTransaction();
        tx.begin();

        try {
            CargoEntity cargo = new CargoEntity();
            cargo.setNama(nama);
            cargo.setAlamat(alamat);
            cargo.setResi(resi);
            cargo.setTanggal(tanggal);
            cargo.setBulan(bulan);

            session.save(cargo); // Simpan data
            tx.commit();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        } catch (HeadlessException e) {
            tx.rollback();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        } finally {
            session.close();
        }
    } 
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        


    }//GEN-LAST:event_SimpanJBActionPerformed

  
public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new Cargo().setVisible(true);
    });
}


    private static class Bulan {

        private static Object getSelectedItem() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Bulan() {
        }
    }

    private static class TFAlamat {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public TFAlamat() {
        }
    }

    private static class TFResi {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public TFResi() {
        }
    }

    private static class Tanggal {

        private static Object getSelectedItem() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Tanggal() {
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JButton DelJB;
    private javax.swing.JButton EditJB;
    private javax.swing.JButton SimpanJB;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFResi;
    private javax.swing.JComboBox<String> Tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class txtBulan {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtBulan() {
        }
    }

    private static class txtnama {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtnama() {
        }
    }

    private static class txtID {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtID() {
        }
    }

    private static class TFId {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public TFId() {
        }
    }

    private static class jTable1 {

        public jTable1() {
        }
    }

   }
